name: SCV API Tests

on:
  push:
    branches: [ "master", "staging" ]
  pull_request:
    branches: [ "master", "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag scv:latest
      
    - name: Run pytest
      run: docker run --name scv_test_container scv:latest /bin/sh -c "pytest --cov=. && coverage xml -i"

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml